import { company, legal, isDraft } from '../site.js';
import { Address, Email, Phone, Field, DraftNotice } from '../components.jsx';

export default function Privacy() {
  return <>
<DraftNotice />
<h2>1. Verantwortlicher</h2><p><Address /></p><p>E-Mail: <Email />{company.phone && <><br />Telefon: <Phone /></>}</p>
{legal.dataProtectionOfficer && <p>Datenschutzbeauftragte Person: <Field text={legal.dataProtectionOfficer} /></p>}
<h2>2. Geltungsbereich</h2><p>Diese Hinweise betreffen die Unternehmenswebsite von ANLUMITH und die Kontaktaufnahme mit uns. Für Echo Music, MyBasar und den App Store gelten die jeweiligen Datenschutzhinweise. Die Produkte sind hier lediglich verlinkt; beim Laden dieser Website werden keine Inhalte dieser Dienste eingebettet.</p>
<h2>3. Bereitstellung der Website</h2><p>{isDraft ? 'Die Veröffentlichung ist über Cloudflare Pages vorgesehen.' : 'Diese Website wird über Cloudflare Pages bereitgestellt.'} Bei der Auslieferung verarbeitet Cloudflare technische Verbindungsdaten, insbesondere IP-Adresse, Zeitpunkt des Abrufs, angeforderte Adresse, Browser- und Geräteinformationen sowie Status- und Sicherheitsinformationen. Diese Daten dienen der Auslieferung und Absicherung der Website sowie der Fehleranalyse.</p><p>Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO. Unser berechtigtes Interesse liegt im zuverlässigen und sicheren Betrieb der Website. Die technischen Verbindungsdaten sind für den Abruf erforderlich; ohne ihre Übermittlung kann die Website nicht ausgeliefert werden.</p><p>Hosting-Dienstleister: Cloudflare, Inc., 101 Townsend Street, San Francisco, CA 94107, USA. Eine Verarbeitung außerhalb der EU bzw. des EWR, insbesondere in den USA, ist möglich.</p><p><strong>Auftragsverarbeitung und internationale Übermittlungen:</strong> <Field text={legal.cloudflareTransferSafeguards} label="geltendes Cloudflare-DPA, anwendbare Transfergarantien und Bezugsmöglichkeit nach Vertragsprüfung" /></p><p><strong>Speicherdauer:</strong> <Field text={legal.hostingRetention} label="tatsächliche Aufbewahrungsfristen bzw. Kriterien der verwendeten Cloudflare-Protokolle" /></p><p>Weitere Informationen: <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare-Datenschutzrichtlinie</a> und <a href="https://www.cloudflare.com/cloudflare-customer-dpa/">Cloudflare Data Processing Addendum</a>.</p>
<h2 id="kontakt">4. Kontakt per E-Mail oder Telefon</h2><p>Wenn du uns kontaktierst, verarbeiten wir deine Kontaktdaten, den Inhalt deiner Nachricht und gegebenenfalls weitere freiwillig übermittelte Angaben, um dein Anliegen zu bearbeiten. Vertragliche und vorvertragliche Anfragen bearbeiten wir auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO. Bei sonstigen Anfragen beruht die Bearbeitung auf Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse ist die Beantwortung deiner Anfrage.</p><p>Die Angaben erfolgen freiwillig. Ohne ausreichende Kontakt- und Sachinformationen können wir deine Anfrage möglicherweise nicht beantworten. Es gibt auf dieser Website kein Kontaktformular.</p><p>Für den Empfang und Versand von E-Mails verwenden wir {legal.emailProvider}</p><p><Field text={legal.emailInternationalTransfers} label="Rollen, Vertragsgrundlage und internationale Übermittlungen bei geschäftlicher Nutzung von iCloud Mail prüfen und beschreiben" /> Weitere Informationen enthält die <a href="https://www.apple.com/de/legal/privacy/">Apple-Datenschutzrichtlinie</a>.</p><p>Wir löschen Anfragen, wenn sie abschließend bearbeitet sind und keine gesetzlichen Aufbewahrungspflichten oder berechtigten Gründe für eine weitere Speicherung bestehen. Bei aufbewahrungspflichtiger Geschäftskorrespondenz richtet sich die Frist nach den einschlägigen handels- und steuerrechtlichen Vorgaben; bei Rechtsansprüchen nach den jeweils geltenden Verjährungsfristen.</p>
<h2>5. Cookies und externe Inhalte</h2><p>Der Website-Code verwendet keine Cookies, keinen Local Storage und keine Analyse- oder Werbeskripte. Schriftarten stammen vom jeweiligen Gerät. Die <a href="/cookies/">Cookie-Hinweise</a> beschreiben auch den gesondert zu prüfenden Einsatz von Cloudflare-Sicherheitsfunktionen. Externe Websites werden erst aufgerufen, wenn du einem entsprechenden Link folgst.</p>
<h2>6. Deine Rechte</h2><p>Unter den gesetzlichen Voraussetzungen hast du das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit (Art. 15–20 DSGVO). Eine erteilte Einwilligung kannst du jederzeit mit Wirkung für die Zukunft widerrufen. Die Rechtmäßigkeit der bisherigen Verarbeitung bleibt davon unberührt.</p><p><strong>Widerspruch:</strong> Soweit wir Daten auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO verarbeiten, kannst du aus Gründen deiner besonderen Situation widersprechen (Art. 21 DSGVO). Wir verarbeiten die Daten dann nur weiter, wenn die gesetzlichen Voraussetzungen dafür bestehen.</p><p>Für diese Rechte kannst du dich an <Email /> wenden. Außerdem kannst du dich bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere am Ort deines gewöhnlichen Aufenthalts, deines Arbeitsplatzes oder des mutmaßlichen Verstoßes. Für unseren Sitz zuständig ist der <a href="https://www.baden-wuerttemberg.datenschutz.de/beschwerde/">Landesbeauftragte für den Datenschutz und die Informationsfreiheit Baden-Württemberg</a>.</p>
<h2>7. Automatisierte Entscheidungen</h2><p>Wir treffen im Rahmen dieser Unternehmenswebsite keine Entscheidungen mit rechtlicher oder vergleichbar erheblicher Wirkung ausschließlich automatisiert und betreiben kein Profiling.</p>
  </>;
}
